### ISSUE TITLE
Move to IPFS Shipyard?

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/ipfs-blob-store#19]
Now we have an org to incubate projects that not part of the core implementation of the protocol or discussion of the spec. That org is [ipfs-shipyard](https://github.com/ipfs-shipyard) created from https://github.com/ipfs/pm/issues/448

Short description:
> IPFS Shipyard is a venue for the community to pursue and collaborate on research experiments, products, code libraries and more around the IPFS project. It is where innovation in userland happens and where we discover and form new primitives to push to the core of IPFS.

Sounds good?

**Comment by diasdavid** [comment]
done :)

@hacdias would you like to give a refresh to this module? Update deps, fix the README and release a new version to npm? I can add you as a npm owner :)

**Comment by hacdias** [comment]
@diasdavid sure thing!

**Comment by hacdias** [comment]
@diasdavid I don't have push access to this repo 😮

**Comment by diasdavid** [comment]
Now you do and also publish permissions :) 

![image](https://user-images.githubusercontent.com/1211152/35343775-4bcbbec8-00e0-11e8-87f5-46e65c4d3b52.png)

**Comment by hacdias** [comment]
Thanks. I've got everything working except one test. I'll get back to it later today :)

**Comment by diasdavid** [comment]
open the PR, I might be able to help :)

**Comment by hacdias** [comment]
Done @diasdavid: #20
